name: mosaiks
channels:
  - conda-forge
dependencies:
  - cudatoolkit
  - fiona
  - rasterio
  - shapely
  - numpy
  - matplotlib
  - pandas
  - pip
  - python
  - pytorch-gpu>=1.7
  - rasterio>=1.0
  - torchvision>=0.3
  - bottle
  - tornado
  - jupyterlab
  - ipykernel
  - rtree>=0.5.0
  - scikit-learn
  - pip:
    - black[colorama]>=21b
    - flake8
    - isort[colors]>=4.3.5
    - mypy>=0.900
    - pytest>=6.0
    - planetary-computer>=0.3.0rc3